apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promotion
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/bravosierrasierra/gitops-cert-level-2-examples.git
      revision: HEAD
      directories:
      - path: environment-promotion/envs/*
  template:
    metadata:
      name: 'env-{{path[0]}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bravosierrasierra/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: '{{path[0]}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[0]}}'
